#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════
# install.sh — Bootstrap installer for PrinterShare
#
# Clones the repo from GitHub, installs Docker CE if missing,
# detects LXC/container environments, and starts the full stack.
#
# One-liner (as root):
#   curl -fsSL https://raw.githubusercontent.com/alal76/printershare/main/scripts/install.sh | sudo bash
#
# Environment overrides:
#   REPO_URL=https://github.com/your-fork/printershare.git
#   BRANCH=main
#   INSTALL_DIR=/opt/printershare
# ═══════════════════════════════════════════════════════════════════════════
set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/alal76/printershare.git}"
BRANCH="${BRANCH:-main}"
INSTALL_DIR="${INSTALL_DIR:-/opt/printershare}"

# ── Helpers ──────────────────────────────────────────────────────────────
info()  { echo -e "\e[1;32m[PrinterShare]\e[0m $*"; }
warn()  { echo -e "\e[1;33m[WARN]\e[0m $*" >&2; }
die()   { echo -e "\e[1;31m[ERROR]\e[0m $*" >&2; exit 1; }
step()  { echo; echo -e "\e[1;34m──────────────────────────────────────────\e[0m"; info "$*"; }

[[ $EUID -ne 0 ]] && die "Run as root:  sudo bash $0"

# ── 1. Detect OS ─────────────────────────────────────────────────────────
step "Detecting operating system..."
[[ -f /etc/os-release ]] || die "/etc/os-release not found — only Ubuntu/Debian are supported."
# shellcheck source=/dev/null
source /etc/os-release
case "${ID:-}" in
  ubuntu|debian) info "OS: ${PRETTY_NAME}" ;;
  *) warn "Untested OS '${ID:-unknown}' — proceeding anyway." ;;
esac

# ── 2. Install system dependencies ───────────────────────────────────────
step "Installing system dependencies..."
apt-get update -qq
apt-get install -y --no-install-recommends \
  ca-certificates curl gnupg lsb-release git

# ── 3. Install Docker CE if missing ──────────────────────────────────────
if ! command -v docker &>/dev/null; then
  step "Installing Docker CE..."
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL "https://download.docker.com/linux/${ID}/gpg" \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/${ID} \
    ${VERSION_CODENAME} stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y docker-ce docker-ce-cli containerd.io \
    docker-buildx-plugin docker-compose-plugin
  systemctl enable --now docker
  info "Docker installed: $(docker --version)"
else
  info "Docker already present: $(docker --version)"
fi

# Verify compose plugin is available
docker compose version &>/dev/null || die "docker compose plugin not found after install."

# ── 4. Clone / update repository ─────────────────────────────────────────
step "Setting up repository at ${INSTALL_DIR}..."
if [[ -d "${INSTALL_DIR}/.git" ]]; then
  info "Updating existing install..."
  git -C "${INSTALL_DIR}" fetch --quiet origin
  git -C "${INSTALL_DIR}" checkout "${BRANCH}"
  git -C "${INSTALL_DIR}" pull --ff-only origin "${BRANCH}"
else
  info "Cloning from ${REPO_URL} (branch: ${BRANCH})..."
  git clone --branch "${BRANCH}" --depth 1 "${REPO_URL}" "${INSTALL_DIR}"
fi
cd "${INSTALL_DIR}"
info "Code at: $(git rev-parse --short HEAD 2>/dev/null || echo 'unknown')"

# ── 5. Set up .env ────────────────────────────────────────────────────────
step "Configuring environment..."
if [[ ! -f .env ]]; then
  cp .env.example .env
  info "Created .env from template. Edit ${INSTALL_DIR}/.env if needed, or use the web wizard."
else
  info ".env already exists — skipping template copy."
fi

# ── 6. Create scan output directory ──────────────────────────────────────
SCANS_PATH="$(grep -E '^SCANS_HOST_PATH=' .env 2>/dev/null | cut -d= -f2- | tr -d '"'"'" || true)"
SCANS_PATH="${SCANS_PATH:-/srv/printershare/scans}"
mkdir -p "${SCANS_PATH}" && chmod 777 "${SCANS_PATH}"
info "Scan output directory: ${SCANS_PATH}"

# ── 7. LXC / container detection → write safe override ───────────────────
IN_LXC=false
if systemd-detect-virt --container -q 2>/dev/null; then
  IN_LXC=true
elif grep -qai 'lxc\|container' /proc/1/environ 2>/dev/null; then
  IN_LXC=true
fi

if $IN_LXC; then
  step "LXC container detected — writing LXC-safe compose override..."
  cat > docker-compose.override.yml <<'LXC_EOF'
# Auto-generated by install.sh for LXC/unprivileged environments.
# Removes USB device mounts that fail without kernel module access.
services:
  cups:
    devices: !reset []
  ipp-usb:
    devices: !reset []
    volumes: !override
      - /var/run/dbus:/var/run/dbus
      - ipp-usb-state:/var/ipp-usb
      - ./ipp-usb/ipp-usb.conf:/etc/ipp-usb/ipp-usb.conf:ro
  scanservjs:
    devices: !reset []
  nfs:
    profiles:
      - disabled
LXC_EOF
  info "LXC override written to docker-compose.override.yml"
elif [[ ! -f docker-compose.override.yml ]]; then
  info "Not in LXC — no override needed."
fi

# ── 8. Build images ───────────────────────────────────────────────────────
step "Building Docker images (this may take several minutes)..."
docker compose --env-file .env build

# ── 9. Start services ─────────────────────────────────────────────────────
step "Starting services..."
docker compose --env-file .env up -d --remove-orphans

# ── 10. Health check ──────────────────────────────────────────────────────
step "Waiting for portal to become healthy..."
TRIES=0
HEALTHY=false
until [[ $TRIES -ge 40 ]]; do
  sleep 3
  if curl -sf http://localhost/api/v1/health 2>/dev/null | grep -q '"status":"ok"'; then
    HEALTHY=true
    break
  fi
  echo -n "."
  (( TRIES++ )) || true
done
echo

SERVER_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"

if $HEALTHY; then
  echo
  info "╔══════════════════════════════════════════════════════════╗"
  info "║  PrinterShare installed and running!                     ║"
  info "║                                                          ║"
  info "║  Open the web UI:  http://${SERVER_IP:-<server-ip>}     ║"
  info "║  Run the setup wizard to configure printers/scanners.    ║"
  info "╚══════════════════════════════════════════════════════════╝"
else
  warn "Services started but health check timed out."
  warn "Check logs: docker compose -f ${INSTALL_DIR}/docker-compose.yml logs --tail 40"
fi

# ── 11. Update reminder ───────────────────────────────────────────────────
echo
info "To update PrinterShare later:  cd ${INSTALL_DIR} && sudo bash scripts/install.sh"
